const WORDS = [
  { word: "ephemeral", pos: "adjective", definition: "Lasting for a very short time.", example: "The cherry blossoms' ephemeral beauty draws crowds every spring.",
    nl: { word: "vergankelijk", pos: "bijvoeglijk naamwoord", definition: "Slechts heel even durend.", example: "De vergankelijke schoonheid van de kersenbloesem trekt elk voorjaar bezoekers." } },
  { word: "petrichor", pos: "noun", definition: "The pleasant, earthy smell after rain falls on dry soil.", example: "She opened the window to let in the petrichor after the storm.",
    nl: { word: "petrichor", pos: "zelfstandig naamwoord", definition: "De aangename, aardse geur na regen op droge grond.", example: "Ze opende het raam om de petrichor na de storm binnen te laten." } },
  { word: "ineffable", pos: "adjective", definition: "Too great or extreme to be expressed in words.", example: "He felt an ineffable sense of relief when the plane finally landed.",
    nl: { word: "onuitsprekelijk", pos: "bijvoeglijk naamwoord", definition: "Te groot of te intens om in woorden uit te drukken.", example: "Hij voelde een onuitsprekelijke opluchting toen het vliegtuig eindelijk landde." } },
  { word: "serendipity", pos: "noun", definition: "The occurrence of events by chance in a happy or beneficial way.", example: "Meeting her old mentor at the airport was pure serendipity.",
    nl: { word: "serendipiteit", pos: "zelfstandig naamwoord", definition: "Het bij toeval iets goeds of waardevols ontdekken.", example: "Haar oude mentor op het vliegveld tegenkomen was puur serendipiteit." } },
  { word: "mellifluous", pos: "adjective", definition: "Sweet or musical; pleasant to hear.", example: "The narrator's mellifluous voice made even the instructions sound poetic.",
    nl: { word: "honingzoet", pos: "bijvoeglijk naamwoord", definition: "Zoetvloeiend en aangenaam om te horen.", example: "De honingzoete stem van de verteller liet zelfs de instructies poëtisch klinken." } },
  { word: "ubiquitous", pos: "adjective", definition: "Present, appearing, or found everywhere.", example: "Smartphones have become ubiquitous in modern life.",
    nl: { word: "alomtegenwoordig", pos: "bijvoeglijk naamwoord", definition: "Overal aanwezig of te vinden.", example: "Smartphones zijn alomtegenwoordig geworden in het moderne leven." } },
  { word: "loquacious", pos: "adjective", definition: "Tending to talk a great deal; talkative.", example: "The loquacious cab driver shared his life story before we even reached the hotel.",
    nl: { word: "praatgraag", pos: "bijvoeglijk naamwoord", definition: "Geneigd om veel te praten; spraakzaam.", example: "De praatgrage taxichauffeur deelde zijn levensverhaal nog voor we het hotel bereikten." } },
  { word: "labyrinthine", pos: "adjective", definition: "Intricate and confusing in structure; maze-like.", example: "We got lost in the labyrinthine alleys of the old town.",
    nl: { word: "labyrintisch", pos: "bijvoeglijk naamwoord", definition: "Ingewikkeld en verwarrend van structuur; als een doolhof.", example: "We verdwaalden in de labyrintische steegjes van de oude stad." } },
  { word: "petulant", pos: "adjective", definition: "Childishly sulky or bad-tempered.", example: "The toddler gave a petulant huff when told it was bedtime.",
    nl: { word: "humeurig", pos: "bijvoeglijk naamwoord", definition: "Kinderachtig mokkend of kortaf.", example: "De peuter blies humeurig toen er gezegd werd dat het bedtijd was." } },
  { word: "nebulous", pos: "adjective", definition: "Vague, unclear, or ill-defined.", example: "Their plans for the future remained nebulous at best.",
    nl: { word: "nevelig", pos: "bijvoeglijk naamwoord", definition: "Vaag, onduidelijk of slecht omschreven.", example: "Hun plannen voor de toekomst bleven op zijn best nevelig." } },
  { word: "quintessential", pos: "adjective", definition: "Representing the most perfect or typical example of something.", example: "With its rolling hills and stone cottages, the village felt quintessentially English.",
    nl: { word: "schoolvoorbeeld", pos: "bijvoeglijk naamwoord", definition: "Het meest typische of perfecte voorbeeld van iets.", example: "Met zijn glooiende heuvels en stenen huisjes voelde het dorp typisch Engels aan." } },
  { word: "surreptitious", pos: "adjective", definition: "Kept secret, especially because it would not be approved of.", example: "He took a surreptitious glance at his phone during the meeting.",
    nl: { word: "heimelijk", pos: "bijvoeglijk naamwoord", definition: "In het geheim gedaan, vooral omdat het niet zou worden goedgekeurd.", example: "Hij wierp tijdens de vergadering een heimelijke blik op zijn telefoon." } },
  { word: "luminous", pos: "adjective", definition: "Full of or giving off light; bright or shining.", example: "The jellyfish glowed with a luminous blue light in the dark water.",
    nl: { word: "lichtgevend", pos: "bijvoeglijk naamwoord", definition: "Vol licht of licht uitstralend; helder of glanzend.", example: "De kwal gaf een lichtgevend blauw schijnsel af in het donkere water." } },
  { word: "cacophony", pos: "noun", definition: "A harsh, discordant mixture of sounds.", example: "The street outside was a cacophony of horns and shouting vendors.",
    nl: { word: "kakofonie", pos: "zelfstandig naamwoord", definition: "Een schril, onharmonieus mengsel van geluiden.", example: "De straat buiten was een kakofonie van claxons en schreeuwende verkopers." } },
  { word: "wistful", pos: "adjective", definition: "Having or showing a feeling of vague or regretful longing.", example: "She gave a wistful smile as she flipped through the old photo album.",
    nl: { word: "weemoedig", pos: "bijvoeglijk naamwoord", definition: "Een vaag, melancholisch verlangen tonend.", example: "Ze glimlachte weemoedig terwijl ze door het oude fotoalbum bladerde." } },
  { word: "perfunctory", pos: "adjective", definition: "Carried out with minimum effort or reflection.", example: "He gave the report a perfunctory glance before signing it.",
    nl: { word: "oppervlakkig", pos: "bijvoeglijk naamwoord", definition: "Uitgevoerd met minimale inspanning of aandacht.", example: "Hij gaf het rapport een oppervlakkige blik voordat hij het ondertekende." } },
  { word: "effervescent", pos: "adjective", definition: "Vivacious and enthusiastic; bubbly.", example: "Her effervescent personality made every gathering more fun.",
    nl: { word: "bruisend", pos: "bijvoeglijk naamwoord", definition: "Levendig en enthousiast; uitbundig.", example: "Haar bruisende persoonlijkheid maakte elke bijeenkomst leuker." } },
  { word: "obfuscate", pos: "verb", definition: "To render something unclear, unintelligible, or obscure.", example: "The company's report seemed designed to obfuscate its declining profits.",
    nl: { word: "verdoezelen", pos: "werkwoord", definition: "Iets onduidelijk, onbegrijpelijk of vaag maken.", example: "Het bedrijfsrapport leek bedoeld om de dalende winsten te verdoezelen." } },
  { word: "pernicious", pos: "adjective", definition: "Having a harmful effect, especially in a gradual or subtle way.", example: "The rumor had a pernicious influence on the team's morale.",
    nl: { word: "verraderlijk", pos: "bijvoeglijk naamwoord", definition: "Schadelijk, vooral op een geleidelijke of subtiele manier.", example: "Het gerucht had een verraderlijke invloed op het teammoreel." } },
  { word: "sonder", pos: "noun", definition: "The realization that each passerby has a complex life entirely invisible to you.", example: "Watching the crowded train platform, he was struck by a quiet sense of sonder.",
    nl: { word: "sonder", pos: "zelfstandig naamwoord", definition: "Het besef dat elke voorbijganger een complex leven heeft dat voor jou onzichtbaar is.", example: "Bij het zien van het drukke perron werd hij getroffen door een stil gevoel van sonder." } },
  { word: "verisimilitude", pos: "noun", definition: "The appearance of being true or real.", example: "The film's attention to detail gave it a remarkable sense of verisimilitude.",
    nl: { word: "geloofwaardigheid", pos: "zelfstandig naamwoord", definition: "De schijn van waarheid of echtheid.", example: "De aandacht voor detail gaf de film een opvallende geloofwaardigheid." } },
  { word: "tenacious", pos: "adjective", definition: "Holding firmly to something; persistent and determined.", example: "Despite the setbacks, she remained tenacious in pursuing her goal.",
    nl: { word: "vastberaden", pos: "bijvoeglijk naamwoord", definition: "Hardnekkig en doelgericht; iets niet snel loslatend.", example: "Ondanks de tegenslagen bleef ze vastberaden haar doel nastreven." } },
  { word: "ebullient", pos: "adjective", definition: "Cheerful and full of energy.", example: "The coach was ebullient after the team's surprise victory.",
    nl: { word: "uitgelaten", pos: "bijvoeglijk naamwoord", definition: "Vrolijk en vol energie.", example: "De coach was uitgelaten na de verrassende overwinning van het team." } },
  { word: "pellucid", pos: "adjective", definition: "Translucently clear; easy to understand.", example: "The lake's pellucid water revealed every pebble on the bottom.",
    nl: { word: "kristalhelder", pos: "bijvoeglijk naamwoord", definition: "Doorzichtig helder; gemakkelijk te begrijpen.", example: "Het kristalheldere water van het meer toonde elk kiezelsteentje op de bodem." } },
  { word: "vicarious", pos: "adjective", definition: "Experienced through another person rather than directly.", example: "He took vicarious pleasure in his daughter's success.",
    nl: { word: "plaatsvervangend", pos: "bijvoeglijk naamwoord", definition: "Ervaren via een ander, niet rechtstreeks.", example: "Hij beleefde plaatsvervangend plezier aan het succes van zijn dochter." } },
  { word: "halcyon", pos: "adjective", definition: "Denoting a period of past time that was idyllically happy and peaceful.", example: "She often thought back to the halcyon days of her childhood summers.",
    nl: { word: "idyllisch", pos: "bijvoeglijk naamwoord", definition: "Verwijzend naar een periode in het verleden die vredig en gelukkig was.", example: "Ze dacht vaak terug aan de idyllische dagen van haar jeugdzomers." } },
  { word: "fastidious", pos: "adjective", definition: "Very attentive to and concerned about accuracy and detail.", example: "The chef was fastidious about the freshness of every ingredient.",
    nl: { word: "kieskeurig", pos: "bijvoeglijk naamwoord", definition: "Zeer nauwgezet en veeleisend op detail.", example: "De chef was kieskeurig over de versheid van elk ingrediënt." } },
  { word: "garrulous", pos: "adjective", definition: "Excessively talkative, especially about trivial matters.", example: "Our garrulous neighbor kept us on the porch for over an hour.",
    nl: { word: "babbelziek", pos: "bijvoeglijk naamwoord", definition: "Overdreven praatziek, vooral over onbenullige zaken.", example: "Onze babbelzieke buurman hield ons meer dan een uur op de veranda vast." } },
  { word: "indelible", pos: "adjective", definition: "Making marks that cannot be removed; impossible to forget.", example: "The trip left an indelible impression on everyone who attended.",
    nl: { word: "onuitwisbaar", pos: "bijvoeglijk naamwoord", definition: "Sporen achterlatend die niet verwijderd kunnen worden; onvergetelijk.", example: "De reis liet bij iedereen een onuitwisbare indruk achter." } },
  { word: "panacea", pos: "noun", definition: "A solution or remedy for all difficulties or diseases.", example: "Exercise is not a panacea, but it helps with many health issues.",
    nl: { word: "panacee", pos: "zelfstandig naamwoord", definition: "Een oplossing of remedie voor alle problemen of ziekten.", example: "Bewegen is geen panacee, maar het helpt bij veel gezondheidsklachten." } },
  { word: "quixotic", pos: "adjective", definition: "Exceedingly idealistic; unrealistic and impractical.", example: "His quixotic plan to sail around the world with no experience worried his friends.",
    nl: { word: "donquichotterig", pos: "bijvoeglijk naamwoord", definition: "Buitensporig idealistisch; onrealistisch en onpraktisch.", example: "Zijn donquichotterige plan om zonder ervaring de wereld rond te zeilen verontrustte zijn vrienden." } },
  { word: "ruminate", pos: "verb", definition: "To think deeply about something.", example: "She liked to ruminate on old letters while sipping her morning tea.",
    nl: { word: "piekeren", pos: "werkwoord", definition: "Diep nadenken over iets.", example: "Ze piekerde graag over oude brieven terwijl ze haar ochtendthee dronk." } },
  { word: "sycophant", pos: "noun", definition: "A person who acts obsequiously toward someone to gain advantage.", example: "The new manager was surrounded by sycophants eager to flatter him.",
    nl: { word: "vleier", pos: "zelfstandig naamwoord", definition: "Iemand die kruiperig doet om voordeel te behalen.", example: "De nieuwe manager werd omringd door vleiers die hem maar wilden behagen." } },
  { word: "torpor", pos: "noun", definition: "A state of physical or mental inactivity; lethargy.", example: "A heavy lunch left him in a torpor for the rest of the afternoon.",
    nl: { word: "loomheid", pos: "zelfstandig naamwoord", definition: "Een staat van lichamelijke of geestelijke inactiviteit; traagheid.", example: "Een zware lunch liet hem de rest van de middag in een loomheid achter." } }
];
